# Generated by Django 2.2.2 on 2019-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=10)),
                ('Catagory', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
