# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prac.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from dialog import Ui_Dialog
from PyQt5.QtWidgets import QPushButton,QVBoxLayout

conn = sqlite3.connect('kills.db')
cursor= conn.cursor()
newcount=0
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.btn_data=[]
        self.btn1_data=[]
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 40, 291, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGeometry(QtCore.QRect(400, 10, 391, 261))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setHorizontalHeaderLabels(['Country','City'])
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 330, 201, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem('Japan',['kyoto','tokyo'])
        self.comboBox.addItem('Usa',['new york','California'])
        self.comboBox.addItem('Russia',['Dagestan','Chechen'])
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(550, 390, 201, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 470, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.showdata)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 400, 200, 50))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(self.tabledata)
        self.buttonBox = QtWidgets.QDialogButtonBox(MainWindow)
        self.buttonBox.setGeometry(QtCore.QRect(222, 222, 200, 323))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 340, 67, 17))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 400, 67, 17))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.comboBox.currentIndexChanged.connect(self.combodata)
        self.combodata(self.comboBox.currentIndex())
        # self.tabledata()
        global newcount
        rwcount=[]
        count = "select count(*) from KILL"
        cursor.execute(count) 
        rowcount = cursor.fetchall()
        print(rowcount,'rowcount')
        rowcounttab= rowcount[0][0]
        rwcount.append(rowcounttab)
        newcount = rwcount[0]
        print(newcount,'--===newcount')

        # layout=QVBoxLayout()
        # self.setLayout(layout)
        for i in range(newcount):
            btn = QPushButton(self.tableWidget)
            btn.setText(str(i))
            btn.setObjectName('button {0}'.format(i))
            self.tableWidget.setCellWidget(i,2,btn)
            self.btn_data.append(btn)
        for q in range(3):
            btn_1 = QPushButton(self.tableWidget)
            btn_1.setText(str(q))
            btn_1.setObjectName('button_q {0}'.format(q))
            self.tableWidget.setCellWidget(q,3,btn_1)
            self.btn1_data.append(btn_1)
       
        

        btn1  = self.btn_data
        for j in btn1:            
            j.clicked.connect(self.clear)
        btn2 = self.btn1_data
        for w in btn2:
            w.clicked.connect(self.check)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(True)
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.pushButton_1.setText(_translate("MainWindow", "show"))


    def combodata(self,index):
        self.comboBox_2.clear()
        cities = self.comboBox.itemData(index)
        if cities:
            self.comboBox_2.addItems(cities)
    
    def showdata(self):
        
        self.country = self.comboBox.currentText()
        self.city = self.comboBox_2.currentText()
        self.label.setText(self.country)
        self.label_2.setText(self.city)

        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        
        

        print('yo its called',self.country,self.city)
    def tabledata(self):
        global newcount
        s = "select Name,Kills from KILL"
        count = "select count(*) from KILL"
        cursor.execute(count) 
        rowcount = cursor.fetchall()
        print(rowcount,'rowcount')
        rowcounttab= rowcount[0][0]
        self.tableWidget.setRowCount(rowcounttab)
        table_index=0
        for i in cursor.execute(s):
            self.tableWidget.setItem(table_index,0,QtWidgets.QTableWidgetItem(str(i[0])))
            self.tableWidget.setItem(table_index,1,QtWidgets.QTableWidgetItem(str(i[1])))
            table_index=table_index+1

    def clear(self):
        row = self.tableWidget.currentRow()
        print(row)
        index = self.tableWidget.item(row,0).text()
        print(index)

    def check(self):
        row1 = self.tableWidget.currentRow()
        print(row1)
        index1=self.tableWidget.item(row1,1).text()
        print(index1)

if __name__ == "__main__":
    import sys
    ##262D37
    app = QtWidgets.QApplication(sys.argv)
    style="""
    QWidget{

        background:#262D37;
        }
    QLabel{
        color:white;
    }
    QTableWidget
    {
        color:white;  
        
        
    }
    QComboBox{
        color:white;
    }
    QFrame{
        color:white;
        border-color:white;
        
      
    }
    QPushButton{
        color:white;
    }


 
    """
    app.setStyleSheet(style)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
